name: Build SM7150 Mainline Kernel v7.1
on:
  workflow_dispatch: # Pemicu manual dari tab Actions di GitHub

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Workflow
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex libelf-dev libssl-dev git python3-minimal-

      - name: Setup Toolchain (GCC AArch64)
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Clone SM7150 Linux Source (Branch v7.1)
        # Menambahkan parameter -b v7.1 untuk mengambil branch spesifik Anda
        run: |
          git clone --depth=1 -b v7.1 github.com kernel

      - name: Compile Kernel
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # Membuat basis konfigurasi dari defconfig generic arm64 mainline
          make defconfig
          
          # Memulai proses kompilasi biner kernel utama dan seluruh file device tree (DTB)
          make -j$(nproc) Image dtbs

      - name: Upload Kernel Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SM7150-Mainline-Image-v7.1
          path: |
            kernel/arch/arm64/boot/Image
            kernel/arch/arm64/boot/dts/qcom/*.dtb
